const http = require('node:http'); const fs = require('node:fs'); const path = require('node:path'); const crypto = require('node:crypto');
const port = process.env.PORT || 3000; const password = process.env.DASHBOARD_PASSWORD; const secret = process.env.SESSION_SECRET; const allowedOrigin = process.env.ALLOWED_ORIGIN || '';
if (!password || !secret) throw new Error('Set DASHBOARD_PASSWORD and SESSION_SECRET before starting.');
const dataFile = path.join(__dirname, 'data', 'invitations.json'); fs.mkdirSync(path.dirname(dataFile), { recursive: true }); if (!fs.existsSync(dataFile)) fs.writeFileSync(dataFile, '[]');
const read = () => JSON.parse(fs.readFileSync(dataFile, 'utf8')); const write = items => fs.writeFileSync(dataFile, JSON.stringify(items, null, 2));
const signed = value => `${value}.${crypto.createHmac('sha256',secret).update(value).digest('hex')}`; const authorized = req => (req.headers.cookie || '').split('; ').some(c => c === `session=${signed('owner')}`);
const body = req => new Promise((resolve,reject)=>{let raw=''; req.on('data',c=>{raw+=c;if(raw.length>10000)req.destroy();});req.on('end',()=>{try{resolve(JSON.parse(raw||'{}'))}catch{reject()}})});
const headers=req=>req.headers.origin===allowedOrigin?{'Access-Control-Allow-Origin':allowedOrigin,'Access-Control-Allow-Credentials':'true','Vary':'Origin'}:{}; const cookieFlags=allowedOrigin?'Secure; SameSite=None;':'SameSite=Strict;'; const send=(res,status,payload,extra={})=>res.writeHead(status,extra).end(payload); const json=(res,status,payload,extra={})=>send(res,status,JSON.stringify(payload),{'Content-Type':'application/json',...extra});
http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`); const cors=headers(req); if(req.method==='OPTIONS')return send(res,204,'',{...cors,'Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type'}); try { if(req.method==='POST'&&url.pathname==='/api/login'){const b=await body(req); if(b.password!==password)return json(res,401,{},cors);return json(res,200,{}, {...cors,'Set-Cookie':`session=${signed('owner')}; HttpOnly; ${cookieFlags} Path=/; Max-Age=28800`});} if(req.method==='POST'&&url.pathname==='/api/logout')return json(res,200,{}, {...cors,'Set-Cookie':`session=; ${cookieFlags} Path=/; Max-Age=0`}); if(req.method==='POST'&&url.pathname==='/api/invitations'){const b=await body(req); if(!b.date||!b.time||!b.mood)return json(res,400,{error:'Missing fields'},cors); const items=read();items.unshift({id:crypto.randomUUID(),date:b.date,time:b.time,mood:b.mood,wish:String(b.wish||'').slice(0,500),boundaries:String(b.boundaries||'').slice(0,500),createdAt:new Date().toISOString()});write(items);return json(res,201,{},cors);} if(req.method==='GET'&&url.pathname==='/api/invitations'){if(!authorized(req))return json(res,401,{},cors);return json(res,200,read(),cors);} if(req.method==='DELETE'&&url.pathname.startsWith('/api/invitations/')){if(!authorized(req))return json(res,401,{},cors);write(read().filter(i=>i.id!==url.pathname.split('/').pop()));return json(res,200,{},cors);} const requested=url.pathname==='/'?'index.html':url.pathname==='/inbox'?'inbox.html':url.pathname.slice(1);const file=path.resolve(__dirname,requested);if(!file.startsWith(__dirname)||!fs.existsSync(file))return send(res,404,'Not found');const type={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'application/javascript'}[path.extname(file)]||'application/octet-stream';send(res,200,fs.readFileSync(file),{'Content-Type':type,'X-Content-Type-Options':'nosniff'});}catch{return json(res,400,{error:'Bad request'},cors);}}).listen(port,()=>console.log(`Open http://localhost:${port}`));
